# Theme Configuration
remote_theme: tajacks/lightspeed
title: "The Lab"
description: "Security research, tools, and random observations"
author:
  name: nickpending
  bio: "Security engineer focused on building tools and breaking things. Into data analysis, problem-solving, BJJ, philosophy, and music production."

# Site Configuration
url: "https://nickpending.github.io"
baseurl: ""

# Plugin Configuration
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific Configuration
theme_config:
  appearance: "auto"  # or "dark" or "light"
  back_home_text: "← Home"
  date_format: "%Y-%m-%d"

# Build Configuration
markdown: kramdown
kramdown:
  input: GFM

# Social Links
social_links:
  github: nickpending
  # twitter: yourhandle
  # linkedin: yourprofile

# Navigation
header_pages:
  - about.md
  - posts.md

# Collections Configuration
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Default Layout Configuration
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
