# Theme Configuration
remote_theme: tajacks/lightspeed
title: "The Lab"
tagline: "Security research, tools, and random observations"
description: "Security research, tools, and random observations"

# Author Configuration
author:
  name: nickpending
  bio: "Security engineer focused on building tools and breaking things. Into data analysis, problem-solving, BJJ, philosophy, and music production."

# Site Configuration
url: "https://nickpending.github.io"
baseurl: ""

# Plugin Configuration
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Theme Configuration
theme_config:
  site_name: "The Lab"
  header_text: "Security research and analysis"
  show_navigation: true
  navigation:
    - name: "Home"
      url: "/"
    - name: "Posts"
      url: "/posts/"
    - name: "About"
      url: "/about/"
  social:
    github: nickpending

# Build Configuration
markdown: kramdown
kramdown:
  input: GFM

# Collections Configuration
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Default Layout Configuration
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
