remote_theme: tajacks/lightspeed
title: "The Lab"
description: "Security research, tools, and random observations"
author:
  name: nickpending
  bio: "Security engineer focused on building tools and breaking things. Into data analysis, problem-solving, BJJ, philosophy, and music production."

# Enable various plugins and features
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Site configuration
url: "https://nickpending.github.io"
baseurl: ""

# Theme-specific settings
social_links:
  github: nickpending
  # Add other social media as needed
  # twitter: yourhandle
  # linkedin: yourprofile

# Navigation
header_pages:
  - about.md
  - archive.md
