# Site Specific Configuration
sitename: "The Lab"
name: "The Lab"
description: "Security research, tools, and random observations"
url: "https://nickpending.github.io"
author: nickpending

# Navigation Links
nav:
  - title: Home
    url: /
  - title: Posts
    url: /posts/
  - title: About
    url: /about/

# Theme Configuration
remote_theme: tajacks/lightspeed

# Plugin Configuration
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Collections Configuration
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Default Layout Configuration
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
