# Site Specific Configuration
sitename: "Voidwire Labs"
name: "Voidwire Labs"
description: "Security research, tools, and random observations"
url: "https://labs.voidwire.info"
baseurl: ""
author: 
  name: nickpending
  github: nickpending
  mastodon: https://infosec.exchange/@nickpending

# Navigation Links
nav:
  - title: Home
    url: /
  - title: Posts
    url: /posts/
  - title: About
    url: /about/

# Keywords - important for SEO
keywords: ['security', 'cybersecurity', 'osint', 'security research', 'vulnerability analysis', 'cybersecurity tools', 'penetration testing', 'security tools']

# Analytics (Plausible requires sign-up)
analytics:
  plausible:
    enabled: true
    site_fqdn: 'labs.voidwire.info'
    script_source: 'https://plausible.io/js/script.js'

# Theme Configuration
remote_theme: tajacks/lightspeed

# Plugin Configuration
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-sitemap

# Collections Configuration
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Default Layout Configuration
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: /assets/images/labs.voidwire.info-preview.svg
      author: nickpending
      lang: en_US
  - scope:
      path: ""
    values:
      layout: "default"
      image: /assets/images/labs.voidwire.info-preview.svg
      lang: en_US

# SEO Specific Settings
social:
  name: nickpending
  links:
    - https://github.com/nickpending
    - https://infosec.exchange/@nickpending

# Category Paginating
autopages:
  enabled: true
  categories:
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    silent: false

# Locale and Language
lang: en_US
locale: en_US

# Build settings
markdown: kramdown

# Exclusions
exclude: [ 'README.md', 'COPYING' ]