# Theme Configuration
remote_theme: tajacks/lightspeed
title: "The Lab"
tagline: "Security research, tools, and random observations"
description: "Security research, tools, and random observations"

# Author Configuration
author:
  name: nickpending
  bio: "Security engineer focused on building tools and breaking things. Into data analysis, problem-solving, BJJ, philosophy, and music production."

# Site Configuration
url: "https://nickpending.github.io"
baseurl: ""

# Plugin Configuration
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Theme Settings
header:
  site_title: "The Lab"
  headline: "Security research and analysis"
  show_nav: true
  nav:
    - title: "Home"
      url: "/"
    - title: "Posts"
      url: "/posts/"
    - title: "About"
      url: "/about/"

# Build Configuration
markdown: kramdown
kramdown:
  input: GFM

# Collections Configuration
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Default Layout Configuration
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
