remote_theme: tajacks/lightspeed
title: "The Lab"
description: "Security research, tools, and random observations"
author:
  name: nickpending
  bio: "Security engineer focused on building tools and breaking things. Into data analysis, problem-solving, BJJ, philosophy, and music production."

# Enable various plugins and features
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Theme configuration
theme_config:
  appearance: "auto"  # or "dark" or "light"
  back_home_text: "← Home"
  date_format: "%Y-%m-%d"

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Site configuration
url: "https://nickpending.github.io"
baseurl: ""

# Theme-specific settings
social_links:
  github: nickpending
  # Add other social media as needed
  # twitter: yourhandle
  # linkedin: yourprofile

# Navigation
header_pages:
  - about.md
  - posts.md

# Site settings
url: "https://nickpending.github.io"
baseurl: ""

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
